version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'root'

  - package-ecosystem: 'npm'
    directory: '/packages/azure-function'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'azure-function'

  - package-ecosystem: 'npm'
    directory: '/packages/cloud-function'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'cloud-function'

  - package-ecosystem: 'npm'
    directory: '/packages/core'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'core'

  - package-ecosystem: 'npm'
    directory: '/packages/lambda'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'lambda'
  - package-ecosystem: 'npm'
    directory: '/packages/lambda/infrastructure/cdk'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'lambda'
      - 'cdk'
  - package-ecosystem: 'npm'
    directory: '/packages/lambda/infrastructure/cdktf'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'lambda'
      - 'cdktf'

  - package-ecosystem: 'npm'
    directory: '/packages/twilio-function'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'twilio-function'
  - package-ecosystem: 'npm'
    directory: '/packages/twilio-function/infrastructure/cdk'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'twilio-function'
      - 'cdktf'

  - package-ecosystem: 'npm'
    directory: '/packages/web-app'
    schedule:
      interval: 'weekly'
    labels:
      - 'npm'
      - 'web-app'
  - package-ecosystem: 'docker'
    directory: '/packages/web-app'
    schedule:
      interval: 'weekly'
    labels:
      - 'docker'
      - 'web-app'
  - package-ecosystem: 'docker'
    directory: '/packages/web-app/api'
    schedule:
      interval: 'weekly'
    labels:
      - 'docker'
      - 'web-app'
      - 'api-docs'
