yarnPath: .yarn/releases/yarn-2.4.0.cjs
packageExtensions:
  'inversify-express-utils@*':
    dependencies:
      'inversify': '*'
  'postman-sandbox@*':
    dependencies:
      'postman-collection': '*'
  'postman-runtime@*':
    dependencies:
      'mime-types': '*'
  'newman@*':
    dependencies:
      'liquid-json': '*'
