packageExtensions:
  inversify-express-utils@*:
    dependencies:
      inversify: '*'
  newman@*:
    dependencies:
      liquid-json: '*'
  postman-runtime@*:
    dependencies:
      mime-types: '*'
  postman-sandbox@*:
    dependencies:
      postman-collection: '*'
  '@cdktf/hcl2json@*':
    dependencies:
      fs-extra: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.0.cjs
