#!/bin/bash
set -e

~/semantic-release -vf -ghr \
    -update shared/package.json \
    -update lambda/package.json \
    -update web-app/package.json

export VERSION=$(cat .version)
gox -ldflags="-s -w" -output="bin/{{.Dir}}_v"$VERSION"_{{.OS}}_{{.Arch}}"
ghr $(cat .ghr) bin/