version: 2
jobs:
  setup:
    working_directory: ~/typescript-inversify-demo
    docker:
      - image: circleci/node:latest
    steps:
      - run: 
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/typescript-inversify-demo
  
  build-shared:
    working_directory: ~/typescript-inversify-demo/shared
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-shared:
    working_directory: ~/typescript-inversify-demo/shared
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run Unit Tests
          command: yarn test
  
  build-web-app:
    working_directory: ~/typescript-inversify-demo/web-app
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-web-app:
    working_directory: ~/typescript-inversify-demo/web-app
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run Unit Tests
          command: yarn test
  
  build-lambda:
    working_directory: ~/typescript-inversify-demo/lambda
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-lambda:
    working_directory: ~/typescript-inversify-demo/lambda
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run Unit Tests
          command: yarn test
  
  terratest-lambda:
    working_directory: ~/typescript-inversify-demo/lambda
    docker:
      - image: circleci/golang:latest
      - image: localstack/localstack:latest
    steps:
      - run:
          name: Install Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
            unzip terraform_0.12.2_linux_amd64.zip -d terraform
      - run:
          name: Install Terragrunt
          command: |
            wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.19.4/terragrunt_linux_amd64
            sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Run API Gateway Terratests
          command: cd modules/api-gateway/test && go test
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  release:
    working_directory: ~/typescript-inversify-demo
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run Semantic Release
          command: npx semantic-release

workflows:
  version: 2
  shared:
    jobs:
      - setup

      - build-shared:
          requires:
            - setup
      - test-shared:
          requires:
            - build-shared

      - build-web-app:
          requires:
            - test-shared
      - test-web-app:
          requires:
            - build-web-app

      - build-lambda:
          requires:
            - test-shared
      - test-lambda:
          requires:
            - build-lambda
      - terratest-lambda:
          requires:
            - test-lambda
      
      - release:
          requires:
            - test-web-app
            - terratest-lambda
          filters:
            branches:
              only: master