version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

references:
  root_directory: &root_directory ~/typescript-inversify-demo
  shared_directory: &shared_directory ~/typescript-inversify-demo/shared
  lambda_directory: &lambda_directory ~/typescript-inversify-demo/lambda
  web_app_directory: &web_app_directory ~/typescript-inversify-demo/web-app

  repo_cache: &repo_cache repo-v1-{{ .Environment.CIRCLE_SHA1 }}
  nodejs_cache: &nodejs_cache node-v1{{ checksum "package.json" }}

  lambda: &lambda lambda
  web_app: &web_app web-app

executors:
  nodejs:
    docker:
      - image: circleci/node:latest

commands:
  install_yarn:
    steps:
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash

  install_nodejs_dependencies:
    steps:
      - run: yarn install

  nodejs_cache_restore:
    steps:
      - restore_cache:
          key: *repo_cache
      - restore_cache:
          key: *nodejs_cache

  lambda_terratests:
    steps:
      - golang_terratests:
          artefact_cache: *lambda

  golang_terratests:
    parameters:
      artefact_cache:
        type: string
      test_directory:
        default: '.'
        type: string
    steps:
      - restore_cache:
          key: *repo_cache
      - restore_cache:
          key: repo-v1-<<parameters.artefact_cache>>-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: go-mod-v1-{{ checksum "<<parameters.artefact_cache>>/go.sum" }}
      - run: wget https://releases.hashicorp.com/terraform/0.12.4/terraform_0.12.4_linux_amd64.zip	&& unzip terraform_0.12.4_linux_amd64.zip && sudo mv terraform /usr/local/bin/	&& chmod +x /usr/local/bin/terraform
      - run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.19.6/terragrunt_linux_amd64	&& sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt && chmod +x /usr/local/bin/terragrunt
      - run:
          name: Run Terratests
          command: cd <<parameters.test_directory>> && go test
      - save_cache:
          key: go-mod-v1-{{ checksum "<<parameters.artefact_cache>>/go.sum" }}
          paths:
            - /go/pkg/mod
jobs:
  setup:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - checkout
      - install_yarn
      - save_cache:
          key: *repo_cache
          paths:
            - *root_directory

  install:
    parameters:
      directory:
        type: string
    working_directory: <<parameters.directory>>
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - install_nodejs_dependencies
      - save_cache:
          key: *nodejs_cache
          paths:
            - node_modules

  lint:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - restore_cache:
          key: node-v1-{{ checksum "shared/package.json" }}
      - restore_cache:
          key: node-v1-{{ checksum "lambda/package.json" }}
      - restore_cache:
          key: node-v1-{{ checksum "web-app/package.json" }}
      - run: yarn lint:all

  unit_test:
    parameters:
      directory:
        type: string
    working_directory: <<parameters.directory>>
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn test:unit

  integration_test:
    parameters:
      directory:
        type: string
    working_directory: <<parameters.directory>>
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn test:integration

  build_artefact:
    parameters:
      directory:
        type: string
      artefact_cache:
        type: string
    working_directory: <<parameters.directory>>
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn build
      - save_cache:
          key: repo-v1-<<parameters.artefact_cache>>-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  terratest:
    parameters:
      directory:
        type: string
    working_directory: <<parameters.directory>>
    docker:
      - image: circleci/golang:latest
    steps:
      - lambda_terratests

  e2e:
    parameters:
      directory:
        type: string
      artefact_cache:
        type: string
    working_directory: <<parameters.directory>>
    docker:
      - image: circleci/golang:latest-node
    steps:
      - restore_cache:
          key: *repo_cache
      - install_yarn
      - install_nodejs_dependencies
      - golang_terratests:
          artefact_cache: <<parameters.artefact_cache>>
          test_directory: e2e

  release:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run:
          name: Run Semantic Release
          command: yarn semantic-release

workflows:
  version: 2
  shared:
    jobs:
      - setup

      - install:
          name: root_install
          directory: *root_directory
          requires:
            - setup
      - install:
          name: shared_install
          directory: *shared_directory
          requires:
            - setup
      - install:
          name: web_app_install
          directory: *web_app_directory
          requires:
            - shared_install
            - setup
      - install:
          name: lambda_install
          directory: *lambda_directory
          requires:
            - shared_install
            - setup

      - lint:
          requires:
            - root_install
            - shared_install
            - web_app_install
            - lambda_install

      - unit_test:
          name: shared_unit_test
          directory: *shared_directory
          requires:
            - lint
      - unit_test:
          name: web_app_unit_test
          directory: *web_app_directory
          requires:
            - lint
      - unit_test:
          name: lambda_unit_test
          directory: *lambda_directory
          requires:
            - lint

      - integration_test:
          name: web_app_integration_test
          directory: *web_app_directory
          requires:
            - web_app_unit_test

      - build_artefact:
          name: build_web_app_artefact
          directory: *web_app_directory
          artefact_cache: *web_app
          requires:
            - web_app_integration_test
      - build_artefact:
          name: build_lambda_artefact
          directory: *lambda_directory
          artefact_cache: *lambda
          requires:
            - lambda_unit_test

      - terratest:
          name: lambda_terratest_api_gateway_module
          directory: ~/typescript-inversify-demo/lambda/modules/api-gateway/test
          requires:
            - build_lambda_artefact
      - terratest:
          name: lambda_terratest_lambda_module
          directory: ~/typescript-inversify-demo/lambda/modules/lambda/test
          requires:
            - build_lambda_artefact
      - terratest:
          name: lambda_terratest_root_module
          directory: ~/typescript-inversify-demo/lambda/terratest
          requires:
            - lambda_terratest_api_gateway_module
            - lambda_terratest_lambda_module

      - e2e:
          name: web_app_e2e
          directory: *web_app_directory
          artefact_cache: *web_app
          requires:
            - build_web_app_artefact
      - e2e:
          name: lambda_e2e
          directory: *lambda_directory
          artefact_cache: *lambda
          requires:
            - lambda_terratest_root_module

      - release:
          requires:
            - web_app_e2e
            - lambda_e2e
          filters:
            branches:
              only: master
