version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

references:
  root_directory: &root_directory ~/typescript-inversify-demo

  repo_cache: &repo_cache repo-v1-{{ .Environment.CIRCLE_SHA1 }}
  nodejs_cache: &nodejs_cache repo-v1-packages-{{ .Environment.CIRCLE_SHA1 }}
  go_cache: &go_cache repo-v1-go-{{ .Environment.CIRCLE_SHA1 }}

  e2e_test: &e2e_test test:e2e
  component_test: &component_test test:component
  integration_test: &integration_test test:integration
  unit_test: &unit_test test:unit

  core: &core core
  lambda: &lambda lambda
  web_app: &web_app web-app

executors:
  nodejs:
    docker:
      - image: circleci/node:12.6.0
  nodejs-golang:
    docker:
      - image: circleci/golang:1.12.7-node

commands:
  nodejs_cache_restore:
    steps:
      - restore_cache:
          key: *repo_cache
      - restore_cache:
          key: *nodejs_cache
      - restore_cache:
          key: repo-v1-core-artefact-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: repo-v1-lambda-artefact-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: repo-v1-web-app-artefact-{{ .Environment.CIRCLE_SHA1 }}

jobs:
  setup:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - checkout
      - save_cache:
          key: *repo_cache
          paths:
            - *root_directory

  install:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn install
      - save_cache:
          key: *nodejs_cache
          paths:
            - node_modules
            - packages/core/node_modules
            - packages/lambda/node_modules
            - packages/web-app/node_modules

  lint:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn lint

  test_executor:
    parameters:
      command:
        type: string
      directory:
        type: string
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: cd packages/<<parameters.directory>> && yarn <<parameters.command>>

  build_artefact:
    parameters:
      cache_path:
        type: string
      directory:
        type: string
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: cd packages/<<parameters.directory>> && yarn build
      - save_cache:
          key: repo-v1-<<parameters.directory>>-artefact-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - <<parameters.cache_path>>

  docker_executor:
    parameters:
      command:
        type: string
      directory:
        type: string
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: *root_directory
    steps:
      - nodejs_cache_restore
      - run: sudo apt-get install -y nodejs
      - run: curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && sudo apt-get update && sudo apt-get install yarn
      - run: sudo apt-get install -y golang-go
      - run: node --version
      - run: go version
      - run: cd packages/<<parameters.directory>> && yarn <<parameters.command>>

  terratest_executor:
    parameters:
      command:
        type: string
      directory:
        type: string
    working_directory: *root_directory
    executor: nodejs-golang
    steps:
      - nodejs_cache_restore
      - restore_cache:
          key: *go_cache
      - run: wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip	&& unzip terraform_0.12.6_linux_amd64.zip && sudo mv terraform /usr/local/bin/	&& chmod +x /usr/local/bin/terraform
      - run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.19.16/terragrunt_linux_amd64	&& sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt && chmod +x /usr/local/bin/terragrunt
      - run: cd packages/<<parameters.directory>> && yarn <<parameters.command>>
      - save_cache:
          key: *go_cache
          paths:
            - /go/pkg/mod

  release:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn semantic-release

workflows:
  version: 2
  shared:
    jobs:
      - setup

      - install:
          requires:
            - setup

      - lint:
          requires:
            - install

      # Core
      - test_executor:
          name: core_unit_test
          command: *unit_test
          directory: *core
          requires:
            - lint

      - build_artefact:
          name: core_build
          cache_path: packages/core/dist
          directory: *core
          requires:
            - core_unit_test

      # lambda
      - test_executor:
          name: lambda_unit_test
          command: *unit_test
          directory: *lambda
          requires:
            - core_build

      - build_artefact:
          name: lambda_build
          cache_path: packages/lambda/modules/lambda/dist
          directory: *lambda
          requires:
            - lambda_unit_test

      - terratest_executor:
          name: lambda_component_test
          command: *component_test
          directory: *lambda
          requires:
            - lambda_build

      - terratest_executor:
          name: lambda_integration_test
          command: *integration_test
          directory: *lambda
          requires:
            - lambda_component_test

      - terratest_executor:
          name: lambda_e2e
          command: *e2e_test
          directory: *lambda
          requires:
            - lambda_integration_test

      #  web app
      - test_executor:
          name: web_app_unit_test
          command: *unit_test
          directory: *web_app
          requires:
            - core_build

      - build_artefact:
          name: web_app_build
          cache_path: packages/web-app/dist
          directory: *web_app
          requires:
            - web_app_unit_test

      - test_executor:
          name: web_app_integration_test
          command: *integration_test
          directory: *web_app
          requires:
            - web_app_build

      - docker_executor:
          name: web_app_e2e
          command: *e2e_test
          directory: *web_app
          requires:
            - web_app_integration_test

      - release:
          requires:
            - lambda_e2e
            - web_app_e2e
          filters:
            branches:
              only: master
