version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

references:
  root_directory: &root_directory ~/typescript-inversify-demo

  repo_cache: &repo_cache repo-v1-{{ .Environment.CIRCLE_SHA1 }}
  nodejs_cache: &nodejs_cache epo-v1-packages-{{ .Environment.CIRCLE_SHA1 }}
  artefact_cache: &artefact_cache repo-v1-artefact-{{ .Environment.CIRCLE_SHA1 }}

executors:
  nodejs:
    docker:
      - image: circleci/node:12.6.0

commands:
  nodejs_cache_restore:
    steps:
      - restore_cache:
          key: *repo_cache
      - restore_cache:
          key: *nodejs_cache
      - restore_cache:
          key: *artefact_cache

jobs:
  setup:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - checkout
      - save_cache:
          key: *repo_cache
          paths:
            - *root_directory

  bootstrap:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn install
      - run: yarn lerna bootstrap
      - save_cache:
          key: *nodejs_cache
          paths:
            - node_modules
            - packages/core/node_modules
            - packages/lambda/node_modules
            - packages/web-app/node_modules

  lint:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn lint

  unit_test:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn lerna run test:unit

  build_artefact:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn lerna run build
      - save_cache:
          key: *artefact_cache
          paths:
            - packages/lambda/dist
            - packages/web-app/dist

  release:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn semantic-release

workflows:
  version: 2
  shared:
    jobs:
      - setup
      - bootstrap:
          requires:
            - setup
      - lint:
          requires:
            - bootstrap
      - unit_test:
          requires:
            - lint
      - build_artefact:
          requires:
            - unit_test
      - release:
          requires:
            - build_artefact
          filters:
            branches:
              only: master
