version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

references:
  root_directory: &root_directory ~/typescript-inversify-demo

  repo_cache: &repo_cache repo-v1-{{ .Environment.CIRCLE_SHA1 }}
  nodejs_cache: &nodejs_cache repo-v1-packages-{{ .Environment.CIRCLE_SHA1 }}
  go_cache: &go_cache repo-v1-go-{{ .Environment.CIRCLE_SHA1 }}
  artefact_cache: &artefact_cache repo-v1-artefact-{{ .Environment.CIRCLE_SHA1 }}

  e2e_test: &e2e_test test:e2e
  component_test: &component_test test:component-test
  integration_test: &integration_test test:integration-test

  lambda: &lambda lambda
  web_app: &web_app web-app

executors:
  nodejs:
    docker:
      - image: circleci/node:12.6.0
  nodejs-golang:
    docker:
      - image: circleci/golang:1.12.7-stretch

commands:
  nodejs_cache_restore:
    steps:
      - restore_cache:
          key: *repo_cache
      - restore_cache:
          key: *nodejs_cache
      - restore_cache:
          key: *artefact_cache

jobs:
  setup:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - checkout
      - save_cache:
          key: *repo_cache
          paths:
            - *root_directory

  bootstrap:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn install
      - run: yarn lerna bootstrap
      - save_cache:
          key: *nodejs_cache
          paths:
            - node_modules
            - packages/core/node_modules
            - packages/lambda/node_modules
            - packages/web-app/node_modules

  lint:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn lint

  unit_test:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn lerna run test:unit

  build_artefact:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn lerna run build
      - save_cache:
          key: *artefact_cache
          paths:
            - packages/lambda/dist
            - packages/web-app/dist

  test_executor:
    parameters:
      command:
        type: string
      scope:
        type: string
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn lerna run --scope <<parameters.scope>> <<parameters.command>>

  terratest_executor:
    parameters:
      command:
        type: string
      scope:
        type: string
    working_directory: *root_directory
    executor: nodejs-golang
    steps:
      - nodejs_cache_restore
      - restore_cache:
          key: *repo_cache
      - run: wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip	&& unzip terraform_0.12.6_linux_amd64.zip && sudo mv terraform /usr/local/bin/	&& chmod +x /usr/local/bin/terraform
      - run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.19.16/terragrunt_linux_amd64	&& sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt && chmod +x /usr/local/bin/terragrunt
      - run: yarn lerna run --scope <<parameters.scope>> <<parameters.command>>
      - save_cache:
          key: *go_cache
          paths:
            - /go/pkg/mod

  release:
    working_directory: *root_directory
    executor: nodejs
    steps:
      - nodejs_cache_restore
      - run: yarn semantic-release

workflows:
  version: 2
  shared:
    jobs:
      - setup

      - bootstrap:
          requires:
            - setup

      - lint:
          requires:
            - bootstrap

      - unit_test:
          requires:
            - lint

      - build_artefact:
          requires:
            - unit_test

      # Component Test
      - terratest_executor:
          name: lambda_component_test
          command: *component_test
          scope: *lambda
          requires:
            - build_artefact

      # Integration Test
      - test_executor:
          name: web_app_integration_test
          command: *integration_test
          scope: *web_app
          requires:
            - build_artefact
      - terratest_executor:
          name: lambda_integration_test
          command: *integration_test
          scope: *lambda
          requires:
            - lambda_component_test

      # E2E
      - terratest_executor:
          name: lambda_e2e
          command: *e2e_test
          scope: *lambda
          requires:
            - lambda_integration_test

      - release:
          requires:
            - web_app_integration_test
            - lambda_e2e
          filters:
            branches:
              only: master
