version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:latest
    steps:
      - run: 
        name: Install Yarn
        command: curl -o- -L https://yarnpkg.com/install.sh | bash
  
  build-shared:
    working_directory: ~/shared
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-shared:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: yarn test
  
  build-web-app:
    working_directory: ~/web-app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-web-app:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: yarn test
  
  build-lambda:
    working_directory: ~/lambda
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-lambda:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: yarn test

workflows:
  version: 2
  shared:
    jobs:
      - setup
      - build-shared:
          requires:
            - setup
      - test-shared:
          requires:
            - build-shared
  web-app:
    jobs:
      - setup
      - build-web-app:
          requires:
            - setup
      - test-web-app:
          requires:
            - build-web-app

  lambda:
    jobs:
      - setup
      - build-lambda:
          requires:
            - setup
      - test-lambda:
          requires:
            - build-lambda