version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/web-app"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/lambda"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/shared"
    update_schedule: "daily"