version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'

  - package_manager: 'javascript'
    directory: '/shared'
    update_schedule: 'daily'

  - package_manager: 'javascript'
    directory: '/web-app'
    update_schedule: 'daily'
  - package_manager: 'docker'
    directory: '/web-app'
    update_schedule: 'daily'
  - package_manager: 'docker'
    directory: '/web-app/api'
    update_schedule: 'daily'

  - package_manager: 'javascript'
    directory: '/lambda'
    update_schedule: 'daily'
  - package_manager: 'terraform'
    directory: '/lambda'
    update_schedule: 'daily'
  - package_manager: 'go:modules'
    directory: '/lambda/terratest'
    update_schedule: 'daily'
  - package_manager: 'go:modules'
    directory: '/lambda/terratest/helper'
    update_schedule: 'daily'
  - package_manager: 'terraform'
    directory: '/lambda/modules/api-gateway'
    update_schedule: 'daily'
  - package_manager: 'go:modules'
    directory: '/lambda/modules/api-gateway/test'
    update_schedule: 'daily'
  - package_manager: 'terraform'
    directory: '/lambda/modules/lambda'
    update_schedule: 'daily'
  - package_manager: 'go:modules'
    directory: '/lambda/modules/lambda/test'
    update_schedule: 'daily'
