version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'

  - package_manager: 'javascript'
    directory: '/packages/azure-function'
    update_schedule: 'daily'

  - package_manager: 'javascript'
    directory: '/packages/cloud-function'
    update_schedule: 'daily'

  - package_manager: 'javascript'
    directory: '/packages/core'
    update_schedule: 'daily'

  - package_manager: 'javascript'
    directory: '/packages/lambda'
    update_schedule: 'daily'

  - package_manager: 'javascript'
    directory: '/packages/web-app'
    update_schedule: 'daily'
  - package_manager: 'docker'
    directory: '/packages/web-app'
    update_schedule: 'daily'
  - package_manager: 'docker'
    directory: '/packages/web-app/api'
    update_schedule: 'daily'
