name: Web App Pipeline

on:
  push:
    paths:
      - '.github/workflows/web-app.yml'
      - 'packages/core/**/*'
      - 'packages/web-app/**/*'

jobs:
  linux-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: yarn install

      - name: Run Core Unit tests
        run: |
          cd packages/core	
          yarn test:unit

      - name: Run Core Build
        run: |
          cd packages/core	
          yarn build

      - name: Run Web App Unit tests
        run: |
          cd packages/web-app
          yarn test:unit

      - name: Build Web App artefact
        run: |
          cd packages/web-app
          yarn build
